# Generated by Django 3.1.2 on 2020-10-03 10:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('github_id', models.CharField(max_length=256)),
                ('user_name', models.CharField(max_length=256)),
                ('data_source', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('github_id', models.CharField(max_length=256)),
                ('data_source', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
