# Generated by Django 3.1.2 on 2020-10-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='data_source',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='repository',
            name='data_source',
            field=models.JSONField(),
        ),
    ]
