# Generated by Django 3.1.2 on 2020-10-03 12:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0006_repository_open_issues_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='developer',
            old_name='user_name',
            new_name='login',
        ),
        migrations.AddField(
            model_name='developer',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='developer',
            name='company',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='developer',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='developer',
            name='email',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='developer',
            name='followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='developer',
            name='following',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='developer',
            name='location',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='developer',
            name='name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='developer',
            name='public_gists',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='developer',
            name='public_repos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='developer',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
