# Generated by Django 3.1.2 on 2020-10-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0008_auto_20201003_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='homepage',
            field=models.TextField(null=True),
        ),
    ]
