# Generated by Django 3.1.2 on 2020-10-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0009_auto_20201003_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='language',
            field=models.TextField(null=True),
        ),
    ]
