# pylint: disable=invalid-name
# Generated by Django 3.1.2 on 2020-10-03 13:48

from django.db import migrations

def find_pk(apps, _schema_editor):
    Developer = apps.get_model('github', 'Developer')
    Repository = apps.get_model('github', 'Repository')

    for repo in Repository.objects.all():
        dev_id = repo.data_source['owner']['id']
        dev = Developer.objects.filter(github_id=dev_id)

        if len(dev) == 1:
            repo.owner = dev[0]
            repo.save()
        else:
            repo.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('github', '0011_repository_owner'),
    ]

    operations = [
        migrations.RunPython(find_pk),
    ]
