# Generated by Django 3.1.2 on 2020-10-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0014_repository_owner_github_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
