# Generated by Django 3.1.2 on 2020-10-03 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0015_auto_20201003_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_limit', models.IntegerField()),
                ('rate_remaining', models.IntegerField()),
                ('rate_reset_raw', models.IntegerField()),
                ('rate_reset', models.DateTimeField()),
            ],
        ),
    ]
