# Generated by Django 3.1.2 on 2020-10-04 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0016_ratelimit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='developer',
            old_name='followers',
            new_name='followers_count',
        ),
        migrations.RenameField(
            model_name='developer',
            old_name='following',
            new_name='following_count',
        ),
    ]
