# Generated by Django 3.1.2 on 2020-10-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0021_developer_starred_repositories'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='stargazers',
            field=models.ManyToManyField(related_name='reverse_stargazers', to='github.Developer'),
        ),
    ]
